language: go

go:
  - 1.6

before_install:
  - go get -v github.com/mattn/goveralls

install:
  - make setup

script:
  - make build-all
  - make test-race
  - make check
  - make bench-race
  - make coveralls
