language: go

go:
  - 1.6

before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - go get -v golang.org/x/tools/cmd/cover

install:
  - make setup

script:
  - make test
  - make race
  - make check || true
  - make coveralls
